### ISSUE TITLE
Doesn't compile on Xcode Version 14.3 (Swift version 5.8)

### ISSUE THREAD

**Issue by otaviocc** [BranchMetrics/mac-branch-deep-linking#36]
### Describe the bug

The project won't compile using either Xcode or Swift build (command line).

```
~/D/T/mac-branch-deep-linking ❯❯❯ swift build                                                                                                                                              ✘ 127 master
Building for debugging...
/Users/me/Developer/Temp/mac-branch-deep-linking/Branch/BranchQRCode.m:115:52: error: 'new' is unavailable
    NSString *branchAPIURL = [[BranchConfiguration new] branchAPIServiceURL];
                                                   ^
/Users/me/Developer/Temp/mac-branch-deep-linking/Branch/BranchMainClass.h:28:1: note: 'init' has been explicitly marked unavailable here
- (instancetype) init NS_UNAVAILABLE;
^
1 error generated.
[7/30] Compiling Branch BNCUserAgentCollector.m
```

Thanks.

### Steps to reproduce

Xcode:

1. Clone the repo
2. Open the project
3. Compile

Swift Package:

1. Clone the repo
2. Run `swift build`

### Expected behavior

It should compile.

### SDK Version

1.4.0

### XCode Version

14.3

### OS

13.2.1

**Comment by otaviocc** [comment]
Hey folks, any updates here? I've updated the PR to match the current behavior, it should be good to go.

**Comment by nsingh-branch** [comment]
This was fixed in the latest release, v1.4.1.
